

# See https://github.com/EmbarkStudios/cargo-about

# cargo license --avoid-dev-deps --avoid-build-deps --filter-platform wasm32-unknown-unknown --features web
# cargo tree --target wasm32-unknown-unknown --features web


accepted = ["MIT", "Apache-2.0", "Unicode-3.0", "Zlib"]
targets = ["wasm32-unknown-unknown"]
ignore-build-dependencies = true
ignore-dev-dependencies = true
