[build]
# target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
# The dependency getrandom needs this flag set, but only when the target is wasm32-unknown-unknown.
# https://docs.rs/getrandom/latest/getrandom/#opt-in-backends
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']
